name: CI depenses assurance maladie 201807

on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"

    pull_request:
      branches:
        - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          rm airflow.cfg
          airflow initdb
          pytest -vv
        env:
          AIRFLOW_HOME: "/home/runner/work/depenses-assurance-maladie-201807/depenses-assurance-maladie-201807"